hamalsolutions/flashtrack-formats-tool

src/App.js
src/components/side-panel.js
src/components/text-editor.js
src/index.js
src/input.css
src/tailwind.css

[FT20-2193](https://hamal-solutions.atlassian.net/browse/FT20-2193)
FE- Crear una función que permita a los usuarios seleccionar de una lista de fuentes existentes o cargar sus propias fuentes

Ft20 2193 fe  crear una función que permita a los usuarios seleccionar de una lista de fuentes existentes o cargar sus propias fuentes

---

package.json
src/App.js
src/components/color-palette.jsx
src/components/side-panel.js

[FT20-2194](https://hamal-solutions.atlassian.net/jira/software/projects/FT20/boards/3?selectedIssue=FT20-2194)

FT20-2194 color picker

---

src/App.js
src/components/fields-editor.js
src/components/side-panel.js

[FT20-2221](https://hamal-solutions.atlassian.net/browse/FT20-2221)
FE- Crear la función para agregar los campos del formato

Ft20 2221 fe crear la función para agregar los campos del formato

---

src/App.js
src/components/color-palette.jsx
src/components/side-panel.js

[FT20-2194](https://hamal-solutions.atlassian.net/jira/software/projects/FT20/boards/3?selectedIssue=FT20-2194)
se agrega un Rect por que de lo contrario al exportar no sale el color de fondo

FT20-2194 redo background color change

---

package-lock.json
package.json
src/App.js
src/components/side-panel.js
src/components/templates.jsx
src/tailwind.css

[FT20-2226](https://hamal-solutions.atlassian.net/browse/FT20-2226)
FE- Crear una función que permita cargar y mostrar los templates

Ft20 2226 fe crear una función que permita cargar y mostrar los templates

---

src/App.js
src/components/fields-editor.js
src/components/side-panel.js

FT20-2221 FE- Crear la función para agregar los campos del formato

FT20-2221 FE- Crear la función para agregar los campos del formato

---

src/App.js
src/components/color-palette.jsx
src/components/image-editor.js
src/components/layers-editor.js
src/components/side-panel.js
src/components/sizelabel-editor.js
src/components/templates.jsx
src/components/text-editor.js
src/components/toolbar-label.js

Implementacion de Zoom (canvas y elementos)
Centrado de etiqueta
Deseleccionado de elementos al exportar, o al cliquear en cualquier area
Implementacion de rotado de etiqueta para generacion
Mejora a nivel de backend para los templates (para uso en generacion de PHP)
Modificacion de fuentes
Modificacion de tipos de codigos de barra basado en los permitidos en el PHP
Implementacion de codigos RGB no solo HEX para el background y textos
Asociacion de fields con textos
Mejora en el sistema de resize de cm y pulgadas y conversiones entre ellos 
Eliminacion de marcar elementos como dinamico

FT20-2197 Tool improvements

---

package-lock.json
package.json
src/index.js

[FT20-2237](https://hamal-solutions.atlassian.net/browse/FT20-2237)
FE Integrar la herramienta de diseño con flashtrak

FT20-2237   FE Integrar la herramienta de diseño con flashtrak

---

src/App.js
src/components/toolbar-label.js

[FT20-2258](https://hamal-solutions.atlassian.net/browse/FT20-2258)

Ft20 2258 aligne an object relative to the canvas

---

src/App.js
src/components/fields-editor.js
src/components/text-editor.js
src/components/toolbar-label.js

La correccion resuelve un problema a la hora de alinear un texto o un field que fueron editados
- [FT20-2258](https://hamal-solutions.atlassian.net/browse/FT20-2258)

FT20-2258-HOTFIX-align-objects-relative-to-canvas

---

src/components/fields-editor.js
src/components/text-editor.js

La correccion resuelve un problema a la hora de alinear un texto o un field que fueron editados
- [FT20-2258](https://hamal-solutions.atlassian.net/browse/FT20-2258)

FT20-2258 Add fontSize event to change box width

---

src/components/toolbar-label.js

FT20-2262 Add X / Y position reference points for fields/text/barcodes (view and edit)

Ft20 2262 add x / y position reference points for fields/text/barcodes (view and edit)

---

src/App.js
src/components/image-editor.js

[FT20-2258](https://hamal-solutions.atlassian.net/browse/FT20-2258)

FT20-2258-hotfix-solve-align-to-images

---

src/components/image-editor.js

[FT20-2258](https://hamal-solutions.atlassian.net/browse/FT20-2258)

FT20-2258 set whidth on image to barcode

---

src/App.js

[FT20-2261](https://hamal-solutions.atlassian.net/browse/FT20-2261)

FT20-2261-add-rulers-invert-rulers

---

src/App.js
src/components/side-panel.js
src/components/text-editor.js
src/components/toolbar-label.js

[FT20-2264](https://hamal-solutions.atlassian.net/browse/FT20-2264)
Alignment of the text with respect to the text box and based on that alignment (anchoring) will be the growth of the text when new characters are entered

Ft20 2264 alignment of the text with respect to the text box and based

---

src/components/text-editor.js
src/components/toolbar-label.js

[FT20-2324](https://hamal-solutions.atlassian.net/browse/FT20-2324)

FT20-2324 Delete font size select

---

src/App.js
src/components/fields-editor.js
src/components/side-panel.js

[FT20-2330](https://hamal-solutions.atlassian.net/browse/FT20-2330)

FT20-2330 add text justification on add fields

---

src/App.js
src/components/fields-editor.js

[FT20-2330](https://hamal-solutions.atlassian.net/browse/FT20-2330)

FT20-2260-solve-field-text-justification-on-element-box

---

src/App.js
src/components/text-editor.js
src/tools/generator.js

[FT20-2344](https://hamal-solutions.atlassian.net/browse/FT20-2344)

FT20-2344-reset-anchor-when-selecting-a-text

---

src/tools/generator.js

[FT20-2350](https://hamal-solutions.atlassian.net/browse/FT20-2350)

FT20-2350-add-the-corresponding-barcode-type-instead-of-just-the-upc
